sudo: required
dist: trusty
language: node_js

node_js:
  - 6

cache:
  directories:
    - node_modules

script:
  - npm test
  - bash <(curl -s https://codecov.io/bash)
  - npm run build

deploy:
   - provider: surge
     project: ./build/
     domain: nefertiti-chat.surge.sh
     on:
       all_branches: true
     skip_cleanup: true
