sudo: required
dist: trusty
language: node_js

node_js:
  - 6

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm run build

cache:
  directories:
    - node_modules

deploy:
  - provider: script
    script: "./deploy.sh"
    on:
      branch: master
  - provider: s3
    access_key_id: "$ARTIFACTS_KEY"
    secret_access_key: "$ARTIFACTS_SECRET"
    bucket: "$ARTIFACTS_BUCKET"
    skip_cleanup: true
    local_dir: build
    on:
      branch: theme/nefertiti-setup
