sudo: required
dist: trusty
language: node_js

node_js:
  - 6

jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm run build

deploy:
  provider: script
  script: "./deploy.sh"

cache:
  directories:
    - node_modules

branches:
  only:
    - master